language:  node_js
node_js:
  - stable

branches:
  except:
    - gh-pages

script:
  - npm run lint
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: dist/angular-tour-of-heroes

